<?php

namespace Tests;

use PathFind\Contracts\PathFindContract;
use PathFind\Exceptions\InvalidCoordinateException;
use PathFind\Exceptions\InvalidMapException;
use PathFind\Exceptions\InvalidPathException;
use PathFind\PathFind;

class PathFindTest extends TestCase
{

    public PathFindContract $pathFind;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->pathFind = new PathFind();
    }

    /** @test */
    public function canFindFastestPathWithSetMap()
    {
        $this->pathFind->setMap($this->maps()['ExampleMap']);
        $result = $this->callPrivateMethod($this->pathFind, 'pathDistance', [[0, 1], [3, 2]]);

        $this->assertEquals(6, $result);
    }

    /** @test */
    public function canFindFastestPathOnRuntime(): void
    {
        $result = $this->pathFind->pathFind($this->maps()['ExampleMap'], [0, 1], [3, 2]);
        $this->assertEquals(6, $result);
    }

    /** @test */
    public function canValidateMap(): void
    {
        $this->expectException(InvalidMapException::class);
        $this->pathFind->pathFind($this->maps()['ExceptionMap'], [0, 1], [0, 4]);
    }

    /** @test */
    public function canValidateNoPath(): void
    {
        $this->pathFind->setMap($this->maps()['NoPathMap']);
        $this->expectException(InvalidPathException::class);
        $this->callPrivateMethod($this->pathFind, 'pathDistance', [[0, 0], [0, 4]]);
    }

    /** @test */
    public function canValidateCoordinates(): void
    {
        $this->expectException(InvalidCoordinateException::class);
        $this->pathFind->pathFind($this->maps()['NoPathMap'], [0, 0], [10, 10]);
    }

    /** @test */
    public function canSolveHardMap(): void
    {
        $this->pathFind->setMap($this->maps()['HardMap']);
        $result = $this->callPrivateMethod($this->pathFind, 'pathDistance', [[0, 0], [4, 4]]);
        $this->assertEquals(16, $result);
    }
}
